# Geo data

This notebook shows how to work with geographic spatial datasets.

In [1]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

import sys
import os

os.chdir("../..")
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
plt.rcParams['axes.facecolor'] = 'white'

In [2]:
from abses.geo import Geo

geo = Geo(1)
geo

In [3]:
geo.setup_from_shape((3, 4))

geo.x
geo.y

(3, 4)

array([0, 1, 2, 3])

array([0, 1, 2])

In [4]:
import xarray as xr

data = np.zeros((3, 4))
data = xr.DataArray(data=data, coords={'x': [1, 2, 3], 'y': [2, 4, 6, 8]})
data

<xarray.DataArray (x: 3, y: 4)>
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])
Coordinates:
  * x        (x) int64 1 2 3
  * y        (y) int64 2 4 6 8

In [5]:
import xarray as xr

data = xr.DataArray(np.zeros((3 ,4)), dims=('x', 'y'))
data.coords

Coordinates:
    *empty*

In [6]:
data = xr.open_dataarray('data/prec_CMFD_V0106_B-01_01mo_010deg_197901-201812.nc')
mean = data.mean('time')


In [9]:
mean.rio.to_raster("data/mean_prec.tif")

In [10]:
mean_prec = xr.open_dataarray('data/mean_prec.tif')
mean_prec.attrs

<xarray.DataArray 'band_data' (band: 1, y: 400, x: 700)>
[280000 values with dtype=float32]
Coordinates:
  * band         (band) int64 1
  * x            (x) float64 70.05 70.15 70.25 70.35 ... 139.7 139.8 139.9 140.0
  * y            (y) float64 15.05 15.15 15.25 15.35 ... 54.65 54.75 54.85 54.95
    spatial_ref  int64 ...
Attributes:
    long_name:  prec

In [45]:
import rioxarray

xda = rioxarray.open_rasterio('data/mean_prec.tif')
xda

<xarray.DataArray (band: 1, y: 400, x: 700)>
[280000 values with dtype=float32]
Coordinates:
  * band         (band) int64 1
  * x            (x) float64 70.05 70.15 70.25 70.35 ... 139.7 139.8 139.9 140.0
  * y            (y) float64 15.05 15.15 15.25 15.35 ... 54.65 54.75 54.85 54.95
    spatial_ref  int64 0
Attributes:
    scale_factor:  1.0
    add_offset:    0.0
    long_name:     prec

In [61]:
from abses.tools.func import make_list
p1 = [.0, -1., -1., -1.]
p2 = [300.0, -1., -1., -1]

p = None
p = np.array(make_list(p))
possible_entries = (p > 0).sum()
# if possible_entries == 0:
#     p = None
# else:
#     p = np.where(p > 0, p, .0)
#     p /= p.sum()

# # solve probability
# if p is None or replace is True:
#     return np.random.choice(a, size=size, replace=replace)
# else:
#     # 如果有概率的实体 少于要选择的实体，优先返回
#     if size is None:
#         return np.random.choice(a, p=p, replace=False)
#     elif possible_entries < size:
#         bounds = a[p > 0]
#         rand = np.random.choice(
#             a[p == 0], size=(size - possible_entries), replace=False
#         )
#         selected = np.concatenate([bounds, rand])
#     else:
#         selected = np.random.choice(a, p=p, size=size, replace=False)

In [63]:
p

array([], dtype=float64)

In [31]:
from abses.factory import PatchFactory

ph = PatchFactory(1, shape=(4, 5))
ph.shape

(4, 5)

In [37]:
data = ph.create_patch(np.zeros((4, 5)), 'tests', False)

In [43]:
ph.geo.x
ph.geo.y

array([0, 1, 2, 3, 4])

array([0, 1, 2, 3])

In [44]:
data.shape

(4, 5)